### PR TITLE
Fixes Issue #6

### PR DESCRIPTION
**Pull request by RyanThomas73**
Issue #6 - Redesigned the patcher to support storing project config values in a separate file. I'm welcome to suggestions for the UI.

### CODE REVIEW

**Comment by lukespragg** [comment]
I don't think is quite what was in mind with splitting the paths. This just adds yet another custom path to the .opj which every user would need to customize if they want to patch for themselves. The storing of the version seems a bit odd too, especially in the format it is in. I think the goal is toe simplify the patcher files and make it a bit smarter in terms of where files are located.

image

Aside from that, there are some minor formatting changes that aren't necessary and go against the format we primarily use, mainly with changing to no space after ifs and such.

**Comment by RyanThomas73** [comment]
Thanks for the feedback so far. How do you feel about standardizing the configuration file as Name.opj.config in the same location as the .opj ?

**Comment by RyanThomas73** [comment]
I can add the newtonsoft Version converter to make the serialization/deserialization correct. I like having it there so future changes can detect the version of the opj and convert if needed.

As for formatting standardization how do you feel about me adding an .editorconfig and/or any other formatting settings configame20@gmail.com files?

**Comment by lukespragg** [comment]
Closing this for now to prevent notification spam of every commit. :P

**Comment by RyanThomas73** [comment]
I think I have a better picture of what is actually desired now. I had originally thought you just wanted certain values in a separate file to make commits slightly easier (e.g. the committer could leave off staging their personal changes to the config file).

Your most recent comment provides me a better picture of the intent of the issue. You're wanting to support a feature of environment based configuration rather than just make project commits a little easier. I'll get to work on adding this.

I'll need to know how you want to address multiple patch projects on the same machine / environment. The config file would need to support per project values, or the patcher would need to support per project config files, or both. I suggest global, per user, and per project config files with a setup like how npm handles it's config files.

What would your preference for format / config filenames be? Personally I would prefer a .json file named something like oxideconfig.json or .oxideconfig. Some alternate options might be:

- Simple text with key value pairs one per line.
- A custom format; .gitconfig files come to mind as an example.


Example:
`
// Project config values would have highest priority
/path/to/same/directory/as/my/patch/project/oxideconfig.json

// Per user config values here would have 2nd highest priority
~/oxideconfig.json

// Global config values would have 3rd highest priority
$PREFIX/etc/oxideconfig.json

// Config values from patcher .exe directory would have lowest priority
/path/to/oxide/patcher/exe/oxideconfig.json
`

**Pull request closed without merging**
