### PR TITLE
Resolves #8 Added CLI support for basic auto-pacthing

### LINKED ISSUE #8: Add command-line support to run without GUI
This is useful for automated patching and builds.

### PR DESCRIPTION
**Pull request by HellUnit**

### CODE REVIEW

**Comment by lukespragg** [comment]
Could we scrap that merge commit please? :)

**Comment by HellUnit** [comment]
Done.

**Comment by lukespragg** [comment]
Not a huge issue, but patching, not pacthing. :p
I'm satisfied otherwise! Thanks.

**Comment by HellUnit** [comment]
LOL. Been misspelling that word all day. Good catch.

**Comment by lukespragg** [comment]
No worries! Thanks for the PR.

**Comment by HellUnit** [comment]
For sure. It still used the misspelled pull request title instead of the commit message. Ugh... Copy/paste fail. Misspelled the commit message and copy/pasted it into the pull request title. Good times.

**Comment by lukespragg** [comment]
My fault there, I could have edited it. No worries though. :)

**Comment by lukespragg** [comment]
I did some testing with this, but it doesn't appear to be working properly, else I am missing how it is supposed to be used. I used "OxidePatcher.exe RustExperimental.opj' from cmd, but it just throws me the error mentioned in #44. Any suggestions/ideas?

**Comment by HellUnit** [comment]
Only thing I could think of is the Target Directory in RustExperimental.opj is incorrect. That is normally the point where the GUI would pop up the error dialog saying the assemblies were missing.

**Comment by lukespragg** [comment]
It is correct, I've been using that file for... 30 or so versions now. ;)

**Comment by HellUnit** [comment]
I'll take a look. All the CLI version does is read the settings from the opj and immediately call the patch method. It doesn't do any of the checks for changed methods via MSIL hashes or anything like the GUI does. It worked when I tested it, but I may have missed something.

**Comment by lukespragg** [comment]
Right, I understand how it works, I just don't understand why it isn't working. I've tried giving the patcher the direct path to the .opj too, but it results in the same error.

**Comment by HellUnit** [comment]
No, it doesn't need a dash. The only time I could get it to throw that error is when Oxide.Core.dll wasn't in the directory with the executable. If the dll is there and the opj is correct, it processes the patch correctly.

**Comment by lukespragg** [comment]
ea8e31c1b5336470b2fa0d2ca94541d9
f84a1150d211531de8167b76773e30c1
17ca96d34252503dbe66fd3a03817be6

**Comment by HellUnit** [comment]
Yeah, I just noticed it specifically says it can't find Oxide.Core.dll, not Assembly-CSharp. Hm.

**Comment by lukespragg** [comment]
Where does it say that?

**Comment by HellUnit** [comment]
LOL. I figured it out. Its because 'manifest' is no longer initialized in PatcherForm. This is where the error is being thrown:
```
string filename = GetAssemblyFilename(manifest.AssemblyName, true);
                if (!File.Exists(filename)) throw new FileNotFoundException(string.Format("Failed to locate target assembly {0}", manifest.AssemblyName), filename);
```

**Comment by HellUnit** [comment]
I meant in the error I was getting when Oxide.Core.dll was missing. It specifically says that it can't find Oxide.Core.dll, whereas yours said Assembly-CSharp. Sorry for the ambiguity.

**Comment by HellUnit** [comment]
No, "var manifest" is initialized in the for loop. My mistake on that one. But at least now I know where to look for what is causing the error.

**Comment by HellUnit** [comment]
Ah. It is looking for Assembly-CSharp_Original FIRST and the exception is thrown when it does not exist. Got it.

**Pull request merged**
