### PR TITLE
Add ExitWhenNonNull Simple hook return behavior

### PR DESCRIPTION
**Pull request by WheteThunger**
This `ExitWhenNonNull` return behavior is different from the legacy `ExitWhenValidType` return behavior only for hooked methods whose return type is boolean. For other methods, the behavior is the same since I'm not sure what we should do in those cases.

ExitWhenValidType (legacy):
```csharp
object returnvar = Interface.CallHook("OnVehicleModuleMove", this, moduleForItem, player);
if (returnvar is bool)
{
    return (bool)returnvar;
}
```

ExitWhenNonNull (new):
```csharp
object returnvar = Interface.CallHook("OnVehicleModuleMove", this, moduleForItem, player);
if (returnvar != null)
{
    return returnvar is bool && (bool)returnvar;
}
```

The difference is that returning a non boolean will result in the hooked method returning false.

### CODE REVIEW

**Comment by WheteThunger** [comment]
I'm still trying to understand why this is necessary in the first place.

My first question would be why do we expect plugin authors to return a non boolean for a hook when the hooked method can only return a boolean? What possible meaning could any other value convey? Would a user do this because we want to allow it for some reason, and we therefore document that as an option? Or should we not allow this and instead consider this user error?

If user error, I can understand if we want to solve that problem, but I dont know if we can reasonably assume that returning `false` is the correct behavior for all cases. It might be better to not handle the return value (same behavior as current) and simply log a warning instead.

Also, @Jake-Rich made a good point in Discord that multiple plugins returning different non null values for the same hook will result in a hook conflict even if they would all resolve to `false` using the logic proposed in this PR. That is probably not desirable, so that is another reason not to merge this PR in its current state.

It would be great to have more information about what prompted this design decision in the first place. What problems have we seen or anticipated with the existing return behavior for boolean methods? Furthermore, are those problems that we want to try to solve in Oxide, given that uMod is where we should be focusing effort?

**Comment by lukespragg** [comment]
The reason this logic exists is because you wanted it to be able to return true or false to affect behavior, not just something to cancel outright.

Boolean hooks are not being added for On hooks anymore, and we aren't adding new Can hooks either. So it'd either be something similar to this logic, only returning to cancel and accepting a default, or not adding the hook until a different method to change behavior of a hook is added in either Oxide or uMod.

**Comment by WheteThunger** [comment]
I'm getting lost in the terminology since I haven't seen any specification for what an On hook or a Can hook is or what constitutes acceptable behavior for them, let alone what "cancel" or "default" is supposed to mean in the context of a non-void method.

**Comment by WheteThunger** [comment]
I don't think we need this for now given that #144 allows us to write some hooks that we couldn't before. We can add a new hook type or return behavior in the future if needed.

This can be closed.

**Pull request closed without merging**
